# -*- coding: utf-8 -*-
from agx.generator.pyegg.utils import (
    class_base_name,
    implicit_dotted_path,
)
from agx.core.util import (
    read_target_node,
    dotted_path,
)
from agx.core.interfaces import IScope
from agx.core import (
    handler,
    Scope,
    registerScope,
    token,
)
from node.ext.uml.interfaces import (
    IOperation,
    IClass,
    IPackage,
    IInterface,
    IInterfaceRealization,
    IDependency,
    IProperty,
    IAssociation,
)

@handler('myhandler2', 'uml2fs', 'semanticsgenerator', 'pyclass')
def myhandler2(self, source, target):
    raise NotImplementedError("stub generated by AGX.")

@handler('myhandler1', 'uml2fs', 'mygenerator', 'packagesandeggs')
def myhandler1(self, source, target):
    raise NotImplementedError("stub generated by AGX.")

@handler('cornicehandler', 'uml2fs', 'semanticsgenerator', 'cornicescope')
def cornicehandler(self, source, target):
    raise NotImplementedError("stub generated by AGX.")