# -*- coding: utf-8 -*-
class MyRestService(object):

    name = myservicename
    path = theurlpath

    def do_something(self):
        raise NotImplementedError("stub generated by AGX.")

    def my_validator(self):
        raise NotImplementedError("stub generated by AGX.")

    def plus_five(self):
        raise NotImplementedError("stub generated by AGX.")